from random import randint          
n=0
guesses=0                                            #the initial guesses count
r=randint(1,50)                                      #a random integer generated by computer
while(n!=r):                                         #loop till he/she gets perfect number
    n=int(input("enter the guessed number:"))        #user input
    if(n>r):                        
        print("the number you guessed is Larger, Smaller number please:")
        guesses+=1
    elif(n<r):
        print("the number you guessed is Smaller, Larger number please:")
        guesses+=1  
print(f"You have guessed a Perfect number! {n} in {guesses} times")     
        